The Gambler's Fallacy
================================
Back to <a href="index.html">Main Page</a>

The Gambler's fallacy, also known as the Monte Carlo fallacy
(because its most famous example happened in a Monte Carlo Casino in
1913),and also referred to as the fallacy of the maturity of chances.

This fallacy is the belief that if deviations from expected behaviour are
observed in repeated independent trials of some random process, future
deviations in the opposite direction are then more likely. (Wikipedia)

#### Monte Carlo 1913
- The most famous example of the gambler's fallacy occurred in a game of roulette at the Monte Carlo Casino on August 18, 1913, when the ball fell in black 26 times in a row. 
- This was an extremely uncommon occurrence, although no more nor less common than any of the other 67,108,863 sequences
of 26 red or black. 
- Gamblers lost millions of francs betting against black, reasoning incorrectly that the streak was causing an "imbalance" in the randomness of the wheel, and that it had to be followed by a long streak of red.


#### Implementation

Firstly let simulate the outcomes of a Roulette Wheel. Something ever
simplistic will suffice here.

- For the sake of simplicity, we will disregard ***Green*** and let  ***Black*** be
signiffied by an outcome of 1 and ***Red*** signified by an outcome of 2.

- For this we will use the `rand()` command, as well as the `ceil()`
command, which rounds a value up to the next highest integer.

In [7]:
X = 2*rand(5)
println(X)


[0.22045338502709333,1.8571431406923953,1.0277811816844475,0.20043715709001297,0.1841501852427263]


In [8]:
println( round(Int32,ceil(X))   ) #One for Red, Two for Black

[1,2,2,1,1]


#### repeated colours

What is of interest is the number of repeated outcomes. 

What we could do is to construct a `for` loop so as to monitor how often a colour repeats.

Each time a new colour comes up, the sequence counter gets set to 1. If the next spin results in the same colour, the sequence number is set to 2, if it happens again, the next sequence number is 3, and so on.

Firstly let set up a basic `for` loop to generate the colours. Ths code is more elaborate than the approach we used already, but it is easy to use this for studying repetitions.


In [9]:
M=100

Colour=[]
for(i in 1:M)
        NextCol = round(Int32,ceil(2*rand(1)))
        Colour = [Colour;NextCol]
end

If the current colour is the same as the last, then the current value in the sequence number vector is 1 more than the last.

Otherwise the current sequence number is reset to 1.

In [10]:
Colour= round(Int32,ceil(2*rand(3)))

3-element Array{Int32,1}:
 1
 2
 1

In [11]:
M=100
for(i in 2:M)
        NextCol = round(Int32,ceil(2*rand(i)))
        Colour = [Colour ; NextCol]
end

In [12]:
M=10000
SeqNo=ones(M)
Colour=round(Int32,ceil(2*rand(M)))

for(i in 2:M)
    if ( Colour[i] == Colour[i-1] )
        SeqNo[i] = SeqNo[i-1]+1  
    end
end

In [13]:
[Colour SeqNo]

10000x2 Array{Float64,2}:
 2.0  1.0
 1.0  1.0
 1.0  2.0
 2.0  1.0
 1.0  1.0
 1.0  2.0
 2.0  1.0
 2.0  2.0
 2.0  3.0
 2.0  4.0
 2.0  5.0
 1.0  1.0
 2.0  1.0
 ⋮       
 1.0  3.0
 2.0  1.0
 2.0  2.0
 1.0  1.0
 1.0  2.0
 2.0  1.0
 1.0  1.0
 2.0  1.0
 1.0  1.0
 2.0  1.0
 2.0  2.0
 2.0  3.0

#### Getting Chain lengths


In [16]:
n=size(SeqNo)[1]
chainlengths=[]
for i in 1:(n-1)
    if SeqNo[i] >= SeqNo[i+1]    
        push!(chainlengths,SeqNo[i])
    end
end
# The last item will necessarily be a chainlength also.
push!(chainlengths,SeqNo[end])

4933-element Array{Any,1}:
 1.0
 2.0
 1.0
 2.0
 5.0
 1.0
 1.0
 1.0
 2.0
 7.0
 3.0
 1.0
 1.0
 ⋮  
 3.0
 3.0
 1.0
 1.0
 3.0
 2.0
 2.0
 1.0
 1.0
 1.0
 1.0
 3.0

In [17]:
sort(chainlengths)

4933-element Array{Any,1}:
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  ⋮  
  9.0
  9.0
  9.0
  9.0
  9.0
  9.0
 10.0
 10.0
 10.0
 11.0
 12.0
 13.0