Transforming Arrays
==========================
<a href="PyDataWorkshop.github.io">Main Page</a> | <a href = "index.html">numpy</a>

### Preliminaries
Here we will import numpy, set up a small numpy array.

In [1]:
import numpy as np
A = range(1,10)
A

range(1, 10)

In [2]:
type(A)

range

In [3]:
A=np.array(A)
type(A)

numpy.ndarray

In [4]:
A

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

<h3><code>reshape()</code></h3>

In [5]:
A = np.reshape(A,(3,3))
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.asmatrix(A)

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [7]:
A.view(np.matrix)

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [8]:
A.shape

(3, 3)

In [9]:
np.shape(A)

(3, 3)

In [10]:
np.size(A)

9

In [11]:
np.ndim(A)

2

In [12]:
I =np.eye(3)
I

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### Vertical Stack

In [13]:
AI = np.vstack((A,I))
AI

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

<h4><code>ravel</code></h4>

In [14]:
np.ravel(AI)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.,  1.,  0.,  0.,  0.,
        1.,  0.,  0.,  0.,  1.])

In [15]:
np.ravel(AI).shape

(18,)

In [16]:
np.tile(A,(2,3))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9, 7, 8, 9],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9, 7, 8, 9]])

In [17]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### matrix flipping

In [18]:
np.fliplr(A)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [19]:
np.flipud(A)

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [20]:
np.diag(A)

array([1, 5, 9])

In [21]:
np.diag(np.diag(A))

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

<h4> Upper and Lower Triangular Matrices </h4>

In [22]:
np.triu(A)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [23]:
np.tril(A)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])