Gambler's Fallacy
======================

In [1]:
import numpy as np

Generate a random series of 0s and 1s

In [17]:
np.random.randint(0,2,size=5)

array([0, 1, 1, 1, 1])

#### Colour Coding

- use pandas Series

In [18]:
import pandas as pd

Colour=pd.Series(["red","black"])

In [19]:
X = np.random.randint(0,2,size=5)
Colour[X]

1    black
0      red
1    black
1    black
1    black
dtype: object

Generate 1000 spins of the wheel¶

In [20]:
N=1000
X = np.random.randint(0,2,size=N)
X[0:10]

array([1, 0, 1, 0, 0, 0, 0, 0, 1, 0])

In [21]:
Colour[X[0:5]]

1    black
0      red
1    black
0      red
0      red
dtype: object

### Remark: 
We will stick to 0s and 1s from now on.

In [22]:
N=10000
SEQ = np.random.randint(0,2,size=N)
print(SEQ[0:50])

[0 1 0 0 0 0 1 0 1 0 1 0 1 1 1 1 1 1 0 1 0 1 1 0 1 0 0 0 1 1 1 0 1 1 0 0 0
 0 1 1 1 0 1 0 1 0 1 0 1 0]


### Question:
Are the first two values the same?

In [23]:
SEQ[0] == SEQ[1]

False

Checking equality of successive pair of values.
I pick 6 and 7 arbitrarily.

In [24]:
y=6
SEQ[y] == SEQ[y+1]

False

In [33]:
#How do ranges work again?
for y in range(0,5):
    print(y)

0
1
2
3
4


In [25]:
   # Look Forward is slightly easier
for y in range(0, 5):
        y=int(SEQ[y] == SEQ[y+1])
        print( '%d' % ( y))  # not covering this much today

0
0
1
1
1


#### `ones_like()` and `zeros_like()`

In [26]:
REPNO = np.ones_like(SEQ)

print(len(REPNO))
print(REPNO[0:5])
type(REPNO)

10000
[1 1 1 1 1]


numpy.ndarray

In [34]:
# LOOKBACK COMPARISON
# first fifteen or so (no need to be precise about this)   

for y in range(1, 16):  
        if SEQ[y] == SEQ[y-1]:    # if same as previous
            REPNO[y]=REPNO[y-1]+1
        else:                     # if not same as previous Reset to 1 
            REPNO[y]=1

#### Output
 - Sequence of 0s and 1s
 - order in sequence

In [35]:
print(SEQ[0:15])
print(REPNO[0:15])
print(max(REPNO))

[0 1 0 0 0 0 1 0 1 0 1 0 1 1 1]
[1 1 1 2 3 4 1 1 1 1 1 1 1 2 3]
4


#### More Simulations

 - Same as before, just more trials

In [38]:
N2=10000000
SEQ2 = np.random.randint(0,2,size=N2)
REPNO2=np.ones_like(SEQ2)

In [39]:
for y in range(1, N2):
        if SEQ2[y] == SEQ2[y-1]:
            REPNO2[y]=REPNO2[y-1]+1
        else:
            REPNO2[y]=1

In [40]:
print(max(REPNO2))

22


#### Exercise
Get the `chain` lengths.


In [46]:
X = np.array([1,3,5,7,11,12,15,16,18,19,20,21])

n = len(X)

In [47]:
for i in range(0,n):
    print(X[i])

1
3
5
7
11
12
15
16
18
19
20
21


In [48]:
X[-1] # indexing from the end

21

In [49]:
np.delete(X,1) # remove an element

array([ 1,  5,  7, 11, 12, 15, 16, 18, 19, 20, 21])

In [50]:
X # not permanent

array([ 1,  3,  5,  7, 11, 12, 15, 16, 18, 19, 20, 21])