Some Useful Linear Algebra Functions
==============================================
<a href="PyDataWorkshop.Github.io">Main Page</a> | <a href="index.html"> numpy </a>

<ol>
<li> <code>det()</code>
<li> <code>solve()</code>
<li> <code>eig()</code>
</ol>

<h4><code>det()</code></h4>
<code>det()</code> computes the determinant of a square matrix or array.

In [14]:
import numpy as np
from numpy.linalg import *

x = np.matrix([1,.5,.5,1])

print(x)
type(x)

[[ 1.   0.5  0.5  1. ]]


numpy.matrixlib.defmatrix.matrix

In [17]:
a = np.matrix('1 2; 3 4')
a

matrix([[1, 2],
        [3, 4]])

In [18]:
b = np.matrix([[1, 2], [3, 4]])
b

matrix([[1, 2],
        [3, 4]])

In [19]:
a * b #matrix Multiplication

matrix([[ 7, 10],
        [15, 22]])

In [22]:
np.array(a) * np.array(b) #element-wise multiplication 
# We are working backwards here

array([[ 1,  4],
       [ 9, 16]])

<h3><code>solve()</code></h3>

<code>solve()</code> solves the system <b>Ax=b</b> when X is square and invertible so that the solution is exact.
\[Ax = b\]



In [23]:
A = np.array([[1.0,2.0,3.0],[3.0,3.0,4.0],[1.0,1.0,4.0]])

b = np.array([[1.0],[2.0],[3.0]])


In [24]:
solve(A,b)



array([[ 0.625],
       [-1.125],
       [ 0.875]])

<h4><code>eig</code></h4>
- <code>eig</code> computes the eigenvalues and eigenvectors of a square matrix. When used with one output, the eigenvalues
and eigenvectors are returned as a tuple.
- <code>eigvals</code> can be used if only eigenvalues are needed.




In [27]:
x = np.matrix([[1,.5],[.5,1]])
val,vec = eig(x)
vec*np.diag(val)*vec.T




matrix([[ 1. ,  0.5],
        [ 0.5,  1. ]])

### Markov Chains