### NumPy Arrays

- Central component of NumPy
- All elements of an Array must be of the same "type".
- Arrays can have any number of dimensions.
    - 2 dimensional arrays , similar to matrices
    - Multidimensional Arrays

In [1]:
import numpy as np



In [2]:
myTuple = (1,2,3,5,6,8)
myList = [1.1,1.5,2.0,4.1] 

print( type(myTuple) )
print( type(myList)  )



<class 'tuple'>
<class 'list'>


In [3]:
A = np.array([1,2,3,4,6])

B = np.array(myTuple)

C = np.array(myList)

print(type(A))
print(type(B))
print(type(C))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
B.dtype

dtype('int32')

In [12]:
C.dtype

dtype('float64')

In [16]:
print(len(B))
print(B.shape)
print(B.size)
print(B.ndim)

6
(6,)
6
1


#### Converting Integer Arrays to Float Arrays

In [29]:
np.array(B,float)

array([ 1.,  2.,  3.,  5.,  6.,  8.])

In [31]:
print(C)
print(np.array(C,complex))

[ 1.1  1.5  2.   4.1]
[ 1.1+0.j  1.5+0.j  2.0+0.j  4.1+0.j]


In [26]:
D=np.array(["a","b","c"])

print(type(D))

print(D.dtype)

<type 'numpy.ndarray'>
|S1


#### Boolean

In [25]:
E=np.array([True,True,False,True])

print(type(E))

print(E.dtype)

<type 'numpy.ndarray'>
bool


#### Multidimensional Arrays

In [32]:
print(A)

[1 2 3 4 6]


In [42]:
F = np.array( [[1,4,5],[4,1,6],[3,2,1]]   )
print(F.shape)

(3, 3)


In [45]:
G=np.array( [[[1,4,5],[4,1,6],[3,2,7]]  , [[1,4,5],[4,1,6],[3,2,1]] ]  )

In [48]:
G.ndim

3

In [49]:
A

array([1, 2, 3, 4, 6])

In [52]:
A[4]

6

In [53]:
F

array([[1, 4, 5],
       [4, 1, 6],
       [3, 2, 1]])

In [56]:
F[:2,0]

array([1, 4])