In [1]:
import numpy as np

X= np.random.rand(5)

In [2]:
X

array([ 0.35346917,  0.48652532,  0.64534871,  0.32189752,  0.80973001])

In [3]:
np.floor(X)

array([ 0.,  0.,  0.,  0.,  0.])

In [5]:
np.ceil(X)

array([ 1.,  1.,  1.,  1.,  1.])

In [6]:
np.sign(X)

array([ 1.,  1.,  1.,  1.,  1.])

In [7]:
np.sum(X)

2.6169707405670999

In [9]:
np.cumsum(X)

array([ 0.35346917,  0.8399945 ,  1.48534321,  1.80724073,  2.61697074])

In [17]:
s = np.random.uniform(0,6,15)

In [21]:
np.sign(0.40-X)

array([ 1., -1., -1.,  1., -1.])

In [18]:
s

array([ 1.30991145,  2.02792687,  2.89496702,  5.83801252,  3.6607868 ,
        3.18961952,  3.22879173,  3.94783835,  2.0189373 ,  3.77689244,
        3.79205632,  5.44858204,  4.25292341,  3.50366895,  0.20671141])

In [19]:
np.ceil(s)

array([ 2.,  3.,  3.,  6.,  4.,  4.,  4.,  4.,  3.,  4.,  4.,  6.,  5.,
        4.,  1.])