### Set Theory Operations

In [5]:
# Union , Intersection and Set Difference

import numpy as np
np.union1d([-1, 0, 1], [-2, 0, 2])

array([-2, -1,  0,  1,  2])

In [6]:
np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])

array([1, 3])

In [7]:
a = np.array([1, 2, 3, 2, 4, 1])
b = np.array([3, 4, 5, 6])
np.setdiff1d(a, b)

np.setdiff1d(b,a)

array([5, 6])

### Three Doors in the Monty Hall Problem


In [8]:
Doors = [1,2,3]

Correct = np.random.choice(Doors,1)
print(Correct)
Choice = np.random.choice(Doors,1)
print(Choice)

[2]
[2]


### Monty Opens a Door
- Monty Picks a Door to Reveal a Goat
- He has to choose an ***incorrect*** door
- Obviously he cant give the answer straight away so he cant pick the chosen door


In [9]:
StayClosed = np.union1d(Correct,Choice)
print(StayClosed)
CanOpen = np.setdiff1d(Doors,StayClosed)
print(CanOpen)

[2]
[1 3]


- There may be either one or two doors in the ***CanOpen*** group. 
- Pick a door at random

In [10]:
RevealGoat = np.random.choice(CanOpen,1)
print(RevealGoat)

[1]


Two Doors Are Still Closed ( no matter what happened previously)

In [11]:
StillClosed = np.setdiff1d(Doors,RevealGoat)
print(RevealGoat)
print(StillClosed)

[1]
[2 3]


### Contestant's Choice
- Contestant can stick or switch
- ***stick*** no change
- ***switch*** change to other unopened door

In [12]:
Stick = Choice
print(Stick)
Switch = np.setdiff1d(StillClosed,Choice)
print(Switch)

[2]
[3]


### Conclusion
- So how did things work out?

In [13]:
print(Stick == Correct)
print(Switch == Correct)

[ True]
[False]


In [14]:
print(int(Stick == Correct))
print(int(Switch == Correct))

1
0


### Write a Function
- Returns "1" if stick was good strategy
- Returns "0" otherwise

In [15]:
def MHstick():
    Doors = [1,2,3]
    Correct = np.random.choice(Doors,1)
    Choice = np.random.choice(Doors,1)
    StayClosed = np.union1d(Correct,Choice)
    CanOpen = np.setdiff1d(Doors,StayClosed)
    Stick = Choice
    Outcome = int(Stick == Correct)
    return (Outcome)


In [16]:
MHstick()

0

In [17]:
for y in range(1, 10):
    print(MHstick())

0
1
1
0
0
0
0
0
0


In [18]:
Count=0
for x in range(0,10000):
    Count = Count + MHstick()
    
print(Count)    

3399
