Setting up Special Arrays with numpy
========================================
<a href="PyDataWorkshop.github.io"> Main Page </a> | <a href="index.html"> numpy </a>

Functions are available to construct a number of useful, frequently encountered arrays.

### Special Arrays

1. ones
2. zeros
3. empty
4. eye and identity


In [3]:
#### Preliminaries

import numpy as np

In [4]:
### Dimensions
U,V,W = 3,4,5

<h2>1. <code>ones()</code></h2>

<ul>

<li> <code>ones</code> generates an array of 1s and is generally called with one argument, a tuple, containing the size of
each dimension. 
<li> <code>ones</code> takes an optional second argument (<code>dtype</code>) to specify the data type.
<li>  If omitted, the
data type is a float.


In [5]:
np.ones((U,V))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [6]:
x2 = np.ones((U,U,V)) # 3D array
x3 = np.ones((U,V), dtype="int32") # 32bit integers
x3

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

<ul>
<li> <code>ones_like</code> creates an array with the same shape and data type as the input.
<li> Calling <code>ones_like(x)</code> is equivalent
to calling <code>ones(x.shape,x.dtype)</code>.
</ul>

In [7]:
A=np.array([[1.0 ,7, 5],
             [5, 6 ,2],
             [4, 3, 1]])

In [8]:
np.ones_like(A)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

<h2>2. <code>zeros()</code></h2>

<ul>
<li> <code>zeros()</code> produces an array of 0s in the same way ones produces an array of 1s.
<li> It is commonly used to initialize
an array to hold values generated by another procedure. 
<li> <code>zeros()</code> takes an optional second argument
(<code>dtype()</code>) to specify the data type.
<li>  If omitted, the data type is float.
</ul>

In [9]:
np.zeros((2,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

<ul>
<li> <code>zeros_like</code> creates an array with the same size and shape as the input. 
<li> Calling <code>zeros_like</code> is equivalent
to calling <code>zeros(x.shape,x.dtype)</code>.
</ul>

In [10]:
z1 = np.zeros((U,V)) # U by V array of 0s
z2 = np.zeros((U,U,V)) # 3D array of 0s
z3 = np.zeros((U,V),dtype="int64") # 64 bit integers



In [11]:
np.zeros_like(A)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

<h2>3. <code>empty()</code></h2>
<ul>
<li> <code>empty()</code> produces an empty (uninitialized) array to hold values generated by another procedure. 
<li> <code>empty()</code> takes
an optional second argument (<code>dtype</code>) which specifies the data type. 
<li> If omitted, the data type is float.
</ul>

In [12]:
np.empty((U,V))

array([[  1.35868053e-321,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000]])

<ul>
<li> Using <code>empty()</code> is slightly faster than calling <code>zeros()</code> 
since it does not assign 0 to all elements of the array –
the “empty” array created will be populated with (essential random) non-zero values. 
<li> <code>empty_like()</code> creates
an array with the same size and shape as the input. 
<li> Calling <code>empty_like(x)</code> is equivalent to calling
<code>empty(x.shape,x.dtype)</code>.
</ul>

<h2>4. <code>eye(), identity()</code></h2>
<ul>
<li> <code>eye()</code> generates an identity array – an array with ones on the diagonal, zeros everywhere else. 
<li> Normally,
an identity array is square and so usually only 1 input is required.
<li> More complex zero-padded arrays
containing an identity matrix can be produced using optional inputs.
<code>identity()</code> is a virtually identical function with similar use, In = identity(N).
<\ul

In [13]:
np.eye(4,dtype="int32")

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [14]:
np.identity(5.7)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [15]:
N=5
In = np.eye(N)

In

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])