Generating Arrays and Matrices
===================================================
Back to <a href="http://pydataworkshop.github.io/">PyDataworkshop site</a> | <a href="http://pydataworkshop.github.io/numpy/">numpy </a>  


<h3><code>linspace(l,u,n)</code></h3>

<code>linspace(l,u,n)}</code> generates a set of n points uniformly spaced between l, a lower bound (inclusive) and u,
an upper bound (inclusive).






In [6]:
from numpy import * 
x = linspace(0, 10, 11)
x


array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

<h3><code>logspace(l,u,n)</code></h3>

<code>logspace(l,u,n)</code> produces a set of logarithmically spaced points between $10^l$ and $10^u$ . 
It is identical to
<code>10**linspace(l,u,n)</code>.

<h3><code>range(l,u,s)</code></h3>

<ul>
<li> <code>range(l,u,s)</code> produces a set of points spaced by s between l, a lower bound (inclusive) and u, an upper
bound (exclusive). 
<li> <code>range()</code> can be used with a single parameter, so that <code>range(n)</code> is equivalent to
<code>range(0,n,1)</code>. 
<li> Note that arange will return integer data type if all inputs are integer.
</ul>



In [7]:
x = range(11)
x

range(0, 11)

In [8]:
x = arange(11.0)

In [10]:
x = arange(4, 10, 1.25)


In [ ]:
### meshgrid
`meshgrid()` broadcasts two vectors to produce two 2-dimensional arrays, 
and is a useful function when plotting 3-dimensional functions.

In [15]:

x = arange(5)
y = arange(3)
print(x)
print(y)

[0 1 2 3 4]
[0 1 2]


In [16]:

X,Y = meshgrid(x,y)



In [17]:
X

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [18]:
Y

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2]])